remote_theme: pages-themes/minimal

title: Olga Vysotska
description: PostDoc in Robotics |  Research Scientist | Software Engineer
logo: /assets/img/olga_img.JPG

linkedin: olga-vysotska-84313256
google_scholar: YwPsGKQAAAAJ

